package rules

import "andon/internal/enums"

// Service keys: a service's rule scope, Env.Datasets key and finding
// source.
const (
	arrSvc         = string(enums.ServiceArr)
	authentikSvc   = string(enums.ServiceAuthentik)
	blacklistSvc   = string(enums.ServiceBlacklist)
	borgSvc        = string(enums.ServiceBorgBackup)
	certsSvc       = string(enums.ServiceCerts)
	dockerSvc      = string(enums.ServiceDocker)
	domainsSvc     = string(enums.ServiceDomains)
	dwdSvc         = string(enums.ServiceDWD)
	freshrssSvc    = string(enums.ServiceFreshRSS)
	gatewaySvc     = string(enums.ServiceGateway)
	giteaSvc       = string(enums.ServiceGitea)
	githubSvc      = string(enums.ServiceGitHub)
	kdestoreSvc    = string(enums.ServiceKDEStore)
	glancesSvc     = string(enums.ServiceGlances)
	gluetunSvc     = string(enums.ServiceGluetun)
	grocySvc       = string(enums.ServiceGrocy)
	hassSvc        = string(enums.ServiceHomeAssistant)
	immichSvc      = string(enums.ServiceImmich)
	jsonapiSvc     = string(enums.ServiceJSONAPI)
	kimaiSvc       = string(enums.ServiceKimai)
	kintsugiSvc    = string(enums.ServiceKintsugi)
	komodoSvc      = string(enums.ServiceKomodo)
	kumaSvc        = string(enums.ServiceUptimeKuma)
	linkwardenSvc  = string(enums.ServiceLinkwarden)
	mailSvc        = string(enums.ServiceMail)
	mediaSvc       = string(enums.ServiceMediaServer)
	nextcloudSvc   = string(enums.ServiceNextcloud)
	ninjaSvc       = string(enums.ServiceInvoiceNinja)
	pangolinSvc    = string(enums.ServicePangolin)
	paperlessSvc   = string(enums.ServicePaperless)
	pgbackSvc      = string(enums.ServicePGBackWeb)
	piholeSvc      = string(enums.ServicePihole)
	proxmoxSvc     = string(enums.ServiceProxmox)
	sabnzbdSvc     = string(enums.ServiceSabnzbd)
	scrutinySvc    = string(enums.ServiceScrutiny)
	speedtestSvc   = string(enums.ServiceSpeedtest)
	sureSvc        = string(enums.ServiceSure)
	tailscaleSvc   = string(enums.ServiceTailscale)
	tibberSvc      = string(enums.ServiceTibber)
	truenasSvc     = string(enums.ServiceTrueNAS)
	umamiSvc       = string(enums.ServiceUmami)
	vaultwardenSvc = string(enums.ServiceVaultwarden)
	wallosSvc      = string(enums.ServiceWallos)
)
